// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navToScreen2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_navToScreen2, 32);
    lv_obj_set_height(ui_navToScreen2, 32);
    lv_obj_set_align(ui_navToScreen2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_x(ui_navToScreen2, -6);
    lv_obj_set_y(ui_navToScreen2, 6);
    lv_obj_add_flag(ui_navToScreen2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_bg_color(ui_navToScreen2, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navToScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navToScreen2Label = lv_label_create(ui_navToScreen2);
    lv_label_set_text(ui_navToScreen2Label, LV_SYMBOL_RIGHT);
    lv_obj_center(ui_navToScreen2Label);
    lv_obj_set_style_text_color(ui_navToScreen2Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_navToScreen2Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_navToScreen2Label, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_GotoScreen2, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_GotoScreen2, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_GotoScreen2, LV_EVENT_RELEASED, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_GotoScreen2, LV_EVENT_PRESS_LOST, NULL);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 234);
    lv_obj_set_height(ui_Panel1, 316);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 233);
    lv_obj_set_height(ui_Panel2, 315);
    lv_obj_set_x(ui_Panel2, 1);
    lv_obj_set_y(ui_Panel2, 0);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -24);
    lv_obj_set_y(ui_Label1, 157);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Temperature");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label1, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 5);
    lv_obj_set_y(ui_Label3, 159);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Humidity");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label3, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -63);
    lv_obj_set_y(ui_Label2, 12);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "°C");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label2, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, 140);
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -30);
    lv_obj_set_y(ui_Label4, 70);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label4, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Label4, "Finishing Goods");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label4, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 35);
    lv_obj_set_y(ui_Label5, -112);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "%");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label5, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_humidValue, 150);
    lv_obj_set_height(ui_humidValue, 150);
    lv_obj_set_x(ui_humidValue, 108);
    lv_obj_set_y(ui_humidValue, 180);
    lv_obj_set_align(ui_humidValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_humidValue, "999.99");
    lv_obj_clear_flag(ui_humidValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humidValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humidValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_humidValue, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidValue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_humidValue, -900, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_humidValue, 700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempValue, 50);
    lv_obj_set_y(ui_tempValue, 52);
    lv_obj_set_align(ui_tempValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_tempValue, "99.99");
    lv_obj_set_style_text_color(ui_tempValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempValue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_tempValue, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 128);
    lv_obj_set_y(ui_Label8, 155);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Update time:");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label8, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_dateValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateValue, 216);
    lv_obj_set_y(ui_dateValue, 78);
    lv_obj_set_align(ui_dateValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_dateValue, "30/04/2025");
    lv_obj_set_style_text_color(ui_dateValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dateValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_dateValue, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeValue, 216);
    lv_obj_set_y(ui_timeValue, 12);
    lv_obj_set_align(ui_timeValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_timeValue, "23:59");
    lv_obj_set_style_text_color(ui_timeValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_timeValue, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 109);
    lv_obj_set_y(ui_Label11, -55);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "AWS:");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label11, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_awsValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_awsValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_awsValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_awsValue, 213);
    lv_obj_set_y(ui_awsValue, -85);
    lv_obj_set_align(ui_awsValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_awsValue, "-");
    lv_obj_set_style_text_color(ui_awsValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_awsValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_awsValue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_awsValue, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 97);
    lv_obj_set_y(ui_Label6, 155);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Sensor Error:");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label6, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorerrorValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_sensorerrorValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensorerrorValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensorerrorValue, 186);
    lv_obj_set_y(ui_sensorerrorValue, 86);
    lv_obj_set_align(ui_sensorerrorValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_sensorerrorValue, "None");
    lv_obj_set_style_text_color(ui_sensorerrorValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensorerrorValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensorerrorValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_sensorerrorValue, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inteneterrorValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_inteneterrorValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_inteneterrorValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_inteneterrorValue, 201);
    lv_obj_set_y(ui_inteneterrorValue, 80);
    lv_obj_set_align(ui_inteneterrorValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_inteneterrorValue, "None");
    lv_obj_set_style_text_color(ui_inteneterrorValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inteneterrorValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inteneterrorValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_inteneterrorValue, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 116);
    lv_obj_set_y(ui_Label7, 155);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Internet Error:");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label7, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidValue1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_humidValue1, 150);
    lv_obj_set_height(ui_humidValue1, 150);
    lv_obj_set_x(ui_humidValue1, 108);
    lv_obj_set_y(ui_humidValue1, 180);
    lv_obj_set_align(ui_humidValue1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_humidValue1, "");
    lv_obj_clear_flag(ui_humidValue1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humidValue1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humidValue1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_humidValue1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidValue1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_humidValue1, -900, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_humidValue1, 700, LV_PART_MAIN | LV_STATE_DEFAULT);

}
