// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrMain_screen_init(void)
{
ui_scrMain = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pnlMain = lv_obj_create(ui_scrMain);
lv_obj_set_width( ui_pnlMain, lv_pct(90));
lv_obj_set_height( ui_pnlMain, lv_pct(90));
lv_obj_set_align( ui_pnlMain, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblMilliseconds = lv_label_create(ui_pnlMain);
lv_obj_set_width( ui_lblMilliseconds, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblMilliseconds, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_lblMilliseconds,"Milliseconds:\n");

ui_lblMillisecondsValue = lv_label_create(ui_pnlMain);
lv_obj_set_width( ui_lblMillisecondsValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblMillisecondsValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblMillisecondsValue, LV_ALIGN_TOP_MID );

ui_btnCount = lv_btn_create(ui_pnlMain);
lv_obj_set_width( ui_btnCount, 100);
lv_obj_set_height( ui_btnCount, 50);
lv_obj_set_align( ui_btnCount, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnCount, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnCount, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblButton = lv_label_create(ui_btnCount);
lv_obj_set_width( ui_lblButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblButton, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblButton,"ClickMe");

ui_lblCount = lv_label_create(ui_pnlMain);
lv_obj_set_width( ui_lblCount, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblCount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblCount, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_lblCount,"Count:");

ui_lblCountValue = lv_label_create(ui_pnlMain);
lv_obj_set_width( ui_lblCountValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblCountValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblCountValue, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_lblCountValue,"Count");

lv_obj_add_event_cb(ui_btnCount, ui_event_btnCount, LV_EVENT_ALL, NULL);

}
