// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrMain_screen_init(void)
{
    ui_scrMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlMain = lv_obj_create(ui_scrMain);
    lv_obj_set_width(ui_pnlMain, lv_pct(90));
    lv_obj_set_height(ui_pnlMain, lv_pct(90));
    lv_obj_set_align(ui_pnlMain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMilliseconds = lv_label_create(ui_pnlMain);
    lv_obj_set_width(ui_lblMilliseconds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMilliseconds, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_lblMilliseconds, "Milliseconds:\n");

    ui_lblMillisecondsValue = lv_label_create(ui_pnlMain);
    lv_obj_set_width(ui_lblMillisecondsValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMillisecondsValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMillisecondsValue, LV_ALIGN_TOP_MID);

    ui_lblCdr = lv_label_create(ui_pnlMain);
    lv_obj_set_width(ui_lblCdr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCdr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCdr, 0);
    lv_obj_set_y(ui_lblCdr, 30);
    lv_label_set_text(ui_lblCdr, "Light:");

    ui_lblCdrValue = lv_label_create(ui_pnlMain);
    lv_obj_set_width(ui_lblCdrValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCdrValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCdrValue, 0);
    lv_obj_set_y(ui_lblCdrValue, 30);
    lv_obj_set_align(ui_lblCdrValue, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCdrValue, "cdr");

    ui_Rotate = lv_btn_create(ui_pnlMain);
    lv_obj_set_width(ui_Rotate, 100);
    lv_obj_set_height(ui_Rotate, 50);
    lv_obj_set_align(ui_Rotate, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Rotate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Rotate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Rotate);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Rotate");

    ui_btnCount = lv_btn_create(ui_pnlMain);
    lv_obj_set_width(ui_btnCount, 100);
    lv_obj_set_height(ui_btnCount, 50);
    lv_obj_set_align(ui_btnCount, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnCount, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblButton = lv_label_create(ui_btnCount);
    lv_obj_set_width(ui_lblButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblButton, "Add 1");

    ui_lblCount = lv_label_create(ui_pnlMain);
    lv_obj_set_width(ui_lblCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCount, 0);
    lv_obj_set_y(ui_lblCount, 60);
    lv_label_set_text(ui_lblCount, "Count:");

    ui_lblCountValue = lv_label_create(ui_pnlMain);
    lv_obj_set_width(ui_lblCountValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCountValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCountValue, 0);
    lv_obj_set_y(ui_lblCountValue, 60);
    lv_obj_set_align(ui_lblCountValue, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCountValue, "0");

    ui_Image1 = lv_img_create(ui_pnlMain);
    lv_img_set_src(ui_Image1, &ui_img_philips_80x106_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Rotate, ui_event_Rotate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnCount, ui_event_btnCount, LV_EVENT_ALL, NULL);

}
